# local debug settings
version: "3.7"
services:
  web-server:
    build:
      target: dev
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
