name: Pull Request Checks
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4  
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.3
