name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
      - merge-pr-actions
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4  
      - name: Run linter script
        run: ./DevTools/scripts/lint_php.sh
  check-unimplemented-readme:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      # use a filter to disable this action unless there's a change to UnimplementedCards
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            UnimplementedCards:
              - 'UnimplementedCards/**'
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Run readme validation script
        run: python UnimplementedCards/generate_md.py validate --verbose
