name: Pull Request Checks
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4  
      - name: Run linter script
        run: ./DevTools/scripts/lint_php.sh
  check-unimplemented-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Run readme validation script
        run: python UnimplementedCards/generate_md.py validate --verbose
