name: Unimplemented Cards Check
on: 
  pull_request:
    paths:
      - 'UnimplementedCards/**'
      - '.github/workflows/unimplementedcards.yml'
jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Run readme script
        run: python UnimplementedCards/generate_md.py --validate
